name: xlider
publish: none
description: xlider for elementary
version: 1.0.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  coolint: 1.0.2

flutter:
